apiVersion: v1
kind: Service
metadata:
  name: taste
spec:
  selector:
    app: taste
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80 for external access (or choose your preferred port)
      targetPort: 8080  # Internal port used by the Spring Boot app
      nodePort: 30081     # Exposed on your node (and accessible via localhost)
  #  type: ClusterIP  # Can change to NodePort if you want external access
  type: NodePort  # Can change to NodePort if you want external access
