name: CI for Taste App

on:
  push:
    branches:
      - main  # Or your main dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: paulthedev007/taste

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${SHORT_SHA} .
          docker push $IMAGE_NAME:${SHORT_SHA}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|\(image: $IMAGE_NAME:\).*|\1${SHORT_SHA}|" kustomize/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kustomize/deployment.yaml
          git commit -m "Update image tag to ${SHORT_SHA}"
          git push
